alter table SCHEDULER_SCHEDULER_LOADER_LOG add column SCHEDULER_VERSION integer ^
update SCHEDULER_SCHEDULER_LOADER_LOG set SCHEDULER_VERSION = 0 where SCHEDULER_VERSION is null ;
alter table SCHEDULER_SCHEDULER_LOADER_LOG alter column SCHEDULER_VERSION set not null ;
