-- begin SCHEDULER_SCHEDULER_LOADER_LOG
alter table SCHEDULER_SCHEDULER_LOADER_LOG add constraint FK_SCHEDULER_LOADER_LOG_SCHEDULED_TASK foreign key (SCHEDULED_TASK_ID) references SYS_SCHEDULED_TASK(ID)^
create unique index IDX_SCHEDULER_LOADER_LOG_UK_SCHEDULED_TASK_ID on SCHEDULER_SCHEDULER_LOADER_LOG (SCHEDULED_TASK_ID) where DELETE_TS is null ^
create unique index IDX_SCHEDULER_LOADER_LOG_UK_CODE on SCHEDULER_SCHEDULER_LOADER_LOG (CODE) where DELETE_TS is null ^
-- end SCHEDULER_SCHEDULER_LOADER_LOG
